function tag = make_param_tag(cfg)
% Names for cache and result files.

n_local = (2 * cfg.diffusion.r + 1) ^ 3;
tag.diffusion = sprintf('r%d_n%d_ka%s_s%d_rho%s_lam%s_dp%s', ...
    cfg.diffusion.r, n_local, number_tag(cfg.diffusion.ka), ...
    cfg.diffusion.steps, number_tag(cfg.diffusion.rho), ...
    number_tag(cfg.diffusion.lambda), ...
    number_tag(cfg.diffusion.distance_power));

temporal = sprintf('tr%s_bp%s-%s_o%d', ...
    number_tag(cfg.temporal.TR), ...
    number_tag(cfg.temporal.low_freq), ...
    number_tag(cfg.temporal.high_freq), ...
    cfg.temporal.filter_order);
tag.task = sprintf('ev%s_fwhm%s_%s_z', ...
    lower(cfg.task.name), number_tag(cfg.task.smooth_fwhm_mm), temporal);
tag.rest = sprintf('%s_pca%d', ...
    temporal, round(cfg.rest.pca_variance * 100));
end

function s = number_tag(x)
s = regexprep(sprintf('%.6g', x), '\.', 'p');
end
